# Generated by Django 4.2.4 on 2023-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], max_length=20, verbose_name='Estado')),
                ('km_rodados', models.PositiveIntegerField(verbose_name='Km Rodados')),
                ('leilao', models.BooleanField(verbose_name='Passagem por Leilão')),
                ('formas_pagamento', models.CharField(max_length=100, verbose_name='Formas de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], max_length=20, verbose_name='Estado')),
                ('km_rodados', models.PositiveIntegerField(verbose_name='Km Rodados')),
                ('leilao', models.BooleanField(verbose_name='Passagem por Leilão')),
                ('formas_pagamento', models.CharField(max_length=100, verbose_name='Formas de Pagamento')),
            ],
        ),
    ]
