# Generated by Django 4.2.4 on 2023-09-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='moto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='motos/', verbose_name='Foto'),
        ),
    ]
