# Generated by Django 4.2.4 on 2023-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro_foto_moto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='formas_pagamento',
            field=models.CharField(choices=[('vista', 'A Vista'), ('parcelado', 'Parcelado')], max_length=20, verbose_name='Formas de Pagamento'),
        ),
    ]
