# Generated by Django 4.2.4 on 2023-09-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_carro_formas_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilitarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], max_length=20, verbose_name='Estado')),
                ('km_rodados', models.PositiveIntegerField(verbose_name='Km Rodados')),
                ('leilao', models.BooleanField(verbose_name='Passagem por Leilão')),
                ('formas_pagamento', models.CharField(choices=[('vista', 'A Vista'), ('parcelado', 'Parcelado')], max_length=20, verbose_name='Formas de Pagamento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Foto')),
            ],
        ),
    ]
