# Generated by Django 4.2.4 on 2023-10-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contato_nome_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='formas_pagamento',
            field=models.CharField(choices=[('vista', 'A Vista'), ('parcelado', 'Parcelado'), ('consorcio', 'Consórcio')], max_length=20, verbose_name='Formas de Pagamento'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='formas_pagamento',
            field=models.CharField(choices=[('vista', 'A Vista'), ('parcelado', 'Parcelado'), ('consorcio', 'Consórcio')], max_length=20, verbose_name='Formas de Pagamento'),
        ),
        migrations.AlterField(
            model_name='utilitarios',
            name='formas_pagamento',
            field=models.CharField(choices=[('vista', 'A Vista'), ('parcelado', 'Parcelado'), ('consorcio', 'Consórcio')], max_length=20, verbose_name='Formas de Pagamento'),
        ),
    ]
