# Generated by Django 4.2.4 on 2023-09-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_utilitarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='utilitarios/', verbose_name='Foto'),
        ),
    ]
