# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestContato():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_contato(self):
        self.driver.get("https://luizhenrique.pythonanywhere.com/")
        self.driver.maximize_window()

        # Rolar a página até o final
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        time.sleep(3)  # Atraso de 3 segundos

        self.driver.find_element(By.ID, "nome").click()
        self.driver.find_element(By.ID, "nome").send_keys("luiz")

        time.sleep(3)  # Atraso de 3 segundos

        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("luiz@gmail.com")

        time.sleep(3)  # Atraso de 3 segundos

        self.driver.find_element(By.ID, "telefone").click()
        self.driver.find_element(By.ID, "telefone").send_keys("123456789")

        time.sleep(3)  # Atraso de 3 segundos

        self.driver.find_element(By.ID, "mensagem").click()
        self.driver.find_element(By.ID, "mensagem").send_keys("teste selenium 5")

        time.sleep(3)  # Atraso de 3 segundos

        self.driver.find_element(By.ID, "button").click()